FROM node:22 AS base
WORKDIR /app
ENV PNPM_HOME="/root/.local/share/pnpm"
ENV PATH="${PATH}:${PNPM_HOME}"
RUN npm install -g pnpm@latest-10
RUN pnpm add turbo --global
COPY package.json package.json
COPY pnpm-lock.yaml pnpm-lock.yaml
COPY pnpm-workspace.yaml pnpm-workspace.yaml
COPY turbo.json turbo.json
COPY biome.json biome.json
COPY packages packages

FROM base AS status-prune
COPY apps/status/package.json apps/status/package.json
RUN turbo prune status --docker

FROM status-prune AS status-installer
COPY --from=status-prune /app/out/json/ .
RUN pnpm install
COPY apps/status apps/status
RUN turbo prune status --docker
COPY --from=status-prune /app/out/full/ .

FROM status-installer AS status-builder
RUN pnpm run ci --filter=status
RUN pnpm run build --filter=status

FROM node:22-slim AS runner
WORKDIR /app
COPY --from=status-builder /app/node_modules /app/node_modules
COPY --from=status-builder /app/packages /app/packages
COPY --from=status-builder /app/apps/status/dist /app/apps/status/dist
COPY --from=status-builder /app/apps/status/node_modules /app/apps/status/node_modules
ENV NODE_ENV=production
EXPOSE 3000
CMD ["node", "/app/apps/status/dist/index.js"]
