FROM node:22 AS base
WORKDIR /app
ENV PNPM_HOME="/root/.local/share/pnpm"
ENV PATH="${PATH}:${PNPM_HOME}"
RUN npm install -g pnpm@latest-10
RUN pnpm add turbo --global
COPY .npmrc .npmrc
COPY package.json package.json
COPY pnpm-lock.yaml pnpm-lock.yaml
COPY pnpm-workspace.yaml pnpm-workspace.yaml
COPY turbo.json turbo.json
COPY biome.json biome.json
COPY packages packages

FROM base AS status-prune
COPY apps/status/package.json apps/status/package.json
RUN turbo prune status --docker

FROM status-prune AS status-installer
COPY --from=status-prune /app/out/json/ .
RUN pnpm install
COPY --from=status-prune /app/out/full/ .

FROM status-installer AS status-builder
COPY apps/status apps/status
RUN pnpm run format --filter=status
RUN pnpm run ci --filter=status
RUN pnpm run build --filter=status

FROM status-builder AS status-deploy
RUN pnpm deploy --filter=status --prod /app/deploy/status

FROM node:22-slim AS runner
WORKDIR /app
COPY --from=status-deploy /app/deploy/status /app/apps/status
ENV NODE_ENV=production
EXPOSE 3000
CMD ["node", "/app/apps/status/dist/index.js"]
