FROM node:22 AS base
WORKDIR /app
ENV PNPM_HOME="/root/.local/share/pnpm"
ENV PATH="${PATH}:${PNPM_HOME}"
RUN npm install -g pnpm@latest-10
RUN pnpm add turbo --global
COPY package.json package.json
COPY pnpm-lock.yaml pnpm-lock.yaml
COPY pnpm-workspace.yaml pnpm-workspace.yaml
COPY turbo.json turbo.json
COPY biome.json biome.json
COPY packages packages

FROM base AS haas_serial-prune
COPY apps/haas_serial/package.json apps/haas_serial/package.json
RUN turbo prune haas_serial --docker

FROM haas_serial-prune AS haas_serial-installer
COPY --from=haas_serial-prune /app/out/json/ .
RUN pnpm install
COPY apps/haas_serial apps/haas_serial
RUN turbo prune haas_serial --docker
COPY --from=haas_serial-prune /app/out/full/ .

FROM haas_serial-installer AS haas_serial-builder
RUN pnpm run ci --filter=haas_serial
RUN pnpm run build --filter=haas_serial

FROM node:22-slim AS runner
WORKDIR /app
COPY --from=haas_serial-builder /app/node_modules /app/node_modules
COPY --from=haas_serial-builder /app/packages /app/packages
COPY --from=haas_serial-builder /app/apps/haas_serial/dist /app/apps/haas_serial/dist
COPY --from=haas_serial-builder /app/apps/haas_serial/node_modules /app/apps/haas_serial/node_modules
ENV NODE_ENV=production
EXPOSE 3000
CMD ["node", "/app/apps/haas_serial/dist/index.js"]
