packages:
  - apps/*
  - packages/*

allowBuilds:
  esbuild: true
  onnxruntime-node: false
  protobufjs: true
  sharp: true
  unrs-resolver: true

ignoredBuildDependencies:
  - onnxruntime-node

onlyBuiltDependencies:
  - esbuild
  - protobufjs
  - sharp
  - unrs-resolver
